spring.application.name=SoftwareProject

spring.datasource.url=jdbc:postgresql://localhost:5432/AMDS_PROJECT
spring.datasource.username=postgres
spring.datasource.password=Arvind@88000

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategySnakeCaseComponent


# LOGGING

# Global logging level
logging.level.root=INFO

# Enable logging for your project packages
logging.level.com.example=INFO

# If your service is in this package (very important)
logging.level.com.example.SoftwareProject=INFO
logging.level.com.example.SoftwareProject.Service=INFO

# Show log output in console
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
#
#server.error.include-message=always
#server.error.include-binding-errors=always
#logging.level.org.springframework=DEBUG


